### ISSUE TITLE
Setup API Gateway repo

### ISSUE THREAD

**Issue by cavis** [PRX/pixel.prx.org#1]
Start out with something similar to [proxy.prx.org](https://github.com/PRX/proxy.prx.org).

- [x] Serve a simple pixel image under the `/i.gif` path
- [x] Allow query params:
  - `?key=<any-string>` can be any string, and will end up under the `key` column in BigQuery
  - any others?
- [x] Filter bot requests

**Comment by brandonhundt** [comment]
`?url=<any-string>` 

example together with the key:
`/i.gif?key=msn&url=https://www.pri.org/stories/2019-04-08/elections-loom-indias-modi-vows-end-terrorism-kashmir-more-military-force`

**Comment by brandonhundt** [comment]
And if the URL needs to be encoded, and/or relative. That works for me.

**Comment by cavis** [comment]
So the `?url` is the _canonical_ url then (not the url it was accessed under, which is the "referer" header).

What is `key=msn` representing in your example?  Since I'm already confused, that probably indicates we need some better query-param / bigquery-field names here.

**Comment by brandonhundt** [comment]
Yes, url is the canonical url.

For the key, I was just thinking that it would simply identify the source feed, because the canonical url could appear in multiple feeds.

**Comment by cavis** [comment]
Okay, plan is that this will track 6 things to bigquery:

1. The `?k=` key query param (any string)
2. The `?c=` canonical-url query param (any string)
3. The `user-agent` header
4. The `x-forwarded-for` header (or fall back to the source-ip of the request)
5. The `referer` header
6. The milliseconds epoch of the request
